#!/bin/bash -ex

exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

export JAVA_OPTS=${java_opts}
export XMX="-Xmx${transactor_xmx}"
export XMS="-Xms${transactor_xms}"

cd /datomic/"datomic-pro"

cat <<EOF >ddb-transactor.properties
################################################################

protocol=${protocol}
host=localhost
port=${port}



################################################################
# See http://docs.datomic.com/storage.html

license-key=${license_key}



################################################################
# See http://docs.datomic.com/storage.html
# DynamoDB storage settings

aws-dynamodb-table=${aws_dynamodb_table}

# See http://docs.amazonwebservices.com/general/latest/gr/rande.html#ddb_region
aws-dynamodb-region=${region}

# To use DynamoDB Local, change the protocol (above) to ddb-local.
# Comment out aws-dynamodb-region, and instead use aws-dynamodb-override-endpoint
# aws-dynamodb-override-endpoint=localhost:8080



################################################################
# See http://docs.datomic.com/storage.html
# This role has read and write access to storage and
# is used by the transactor to read and write data. Optionally,
# this role also has write access to an S3 bucket used for log
# storage and to CloudWatch for metrics, if those features are
# enabled.
# (Can be auto-generated by bin/datomic ensure-transactor.)

aws-transactor-role=${transactor_role}



################################################################
# See http://docs.datomic.com/storage.html
# This role has read-only access to storage and
# is used by peers to read data.
# (Can be auto-generated by bin/datomic ensure-transactor.)

aws-peer-role=${peer_role}



################################################################
# See http://docs.datomic.com/capacity.html


# Recommended settings for -Xmx4g production usage.
memory-index-threshold=${memory_index_threshold}
memory-index-max=${memory_index_max}
object-cache-max=${object_cache_max}

# Recommended settings for -Xmx1g usage, e.g. dev laptops.
# memory-index-threshold=${memory_index_threshold}
# memory-index-max=${memory_index_max}
# object-cache-max=${object_cache_max}



## OPTIONAL ####################################################


# Set to false to disable SSL between the peers and the transactor.
# Default: true
# encrypt-channel=true

# Data directory is used for dev: and free: storage, and
# as a temporary directory for all storages.
# data-dir=data

# Transactor will log here, see bin/logback.xml to configure logging.
# log-dir=log

# Transactor will write process pid here on startup
# pid-file=transactor.pid



## OPTIONAL ####################################################
# See http://docs.datomic.com/storage.html
# Memcached configuration.

# memcached=host:port,host:port,...
# memcached-username=datomic
# memcached-password=datomic



## OPTIONAL ####################################################
# See http://docs.datomic.com/capacity.html


# Soft limit on the number of concurrent writes to storage.
# Default: 4, Miniumum: 2
# write-concurrency=4

# Soft limit on the number of concurrent reads to storage.
# Default: 2 times write-concurrency, Miniumum: 2
# read-concurrency=8



## OPTIONAL ####################################################
# See http://docs.datomic.com/aws.html
# Optional settings for rotating logs to S3
# (Can be auto-generated by bin/datomic ensure-transactor.)

aws-s3-log-bucket-id=${s3_log_bucket}




## OPTIONAL ####################################################
# See http://docs.datomic.com/aws.html
# Optional settings for Cloudwatch metrics.
# (Can be auto-generated by bin/datomic ensure-transactor.)

aws-cloudwatch-region=${region}


# Pick a unique name to distinguish transactor metrics from different systems.
aws-cloudwatch-dimension-value=${cloudwatch_dimension}



## OPTIONAL ####################################################
# See http://docs.datomic.com/ha.html


# The transactor will write a heartbeat into storage on this interval.
# A standby transactor will take over if it sees the heartbeat go
# unwritten  for 2x this interval. If your transactor load leads to
# long gc pauses, you can increase this number to prevent the standby
# transactor from unnecessarily taking over during a long gc pause.
# Default: 5000, Miniumum: 5000
# heartbeat-interval-msec=5000



## OPTIONAL ####################################################


# The transactor will use this partition for new entities that
# do not explicitly specify a partition.
# Default: :db.part/user
# default-partition=:db.part/user


EOF

chmod 744 ddb-transactor.properties

bin/transactor ddb-transactor.properties || true
echo "Transactor process stopped. Shutting down."
