version: 0.2

phases:
  install:
    commands:
      - echo Install step...
      - pip install awscli --upgrade --user
      - echo `aws --version`
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws ecr get-login --region ${region} --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build ${build_args} -t ${source_repository_url}:${image_tag} .
      - docker tag ${source_repository_url}:${image_tag} ${target_repository_url}:${image_tag}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing latest Docker image to Amazon ECR...
      - docker push ${target_repository_url}:${image_tag}
      - echo Write image definitions json file...
      - printf '[{"name":"%s","imageUri":"%s"}]' ${source_repository_url} ${target_repository_url}:${image_tag} > imagedefinitions.json
      - echo Upgrade task definitions
      - aws ecs run-task --launch-type FARGATE --task-definition ${task} --cluster ${cluster} --network-configuration "awsvpcConfiguration={subnets=${subnets},securityGroups=[${security_groups}]}"

artifacts:
  files: imagedefinitions.json
