#!/bin/bash -ex

exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

export XMX="-Xmx${xmx}"
export XMS="-Xms${xms}"
export JAVA_OPTS=${java_opts}

cd /datomic/"datomic-pro"

echo "Create properties file..."
cat <<EOF >ddb-transactor.properties
################################################################

host=`curl http://instance-data/latest/meta-data/local-ipv4`
protocol=${protocol}
port=${port}
license-key=${license_key}

## STORAGE #####################################################
# See http://docs.datomic.com/storage.html

aws-dynamodb-table=${dynamodb_table}
aws-dynamodb-region=${region}

## LOGS ########################################################

aws-s3-log-bucket-id=${s3_log_bucket}
aws-cloudwatch-region=${region}
aws-cloudwatch-dimension-value=${cloudwatch_dimension}

## TRANSACTOR ROLE #############################################
# This role has read and write access to storage and
# is used by the transactor to read and write data. Optionally,
# this role also has write access to an S3 bucket used for log
# storage and to CloudWatch for metrics, if those features are
# enabled.
# (Can be auto-generated by bin/datomic ensure-transactor.)

aws-transactor-role=${transactor_role}

## PEER ROLE ###################################################
# This role has read-only access to storage and
# is used by peers to read data.
# (Can be auto-generated by bin/datomic ensure-transactor.)

aws-peer-role=

################################################################

memory-index-threshold=${memory_index_threshold}
memory-index-max=${memory_index_max}
object-cache-max=${object_cache_max}

# Set to false to disable SSL between the peers and the transactor.
# Default: true
# encrypt-channel=true

# Data directory is used for dev: and free: storage, and
# as a temporary directory for all storages.
# data-dir=data

# Transactor will log here, see bin/logback.xml to configure logging.
# log-dir=log

# Transactor will write process pid here on startup
# pid-file=transactor.pid

# Memcached configuration.
# memcached=host:port,host:port,...
# memcached-username=datomic
# memcached-password=datomic

# Soft limit on the number of concurrent writes to storage.
# Default: 4, Miniumum: 2
# write-concurrency=4

# Soft limit on the number of concurrent reads to storage.
# Default: 2 times write-concurrency, Miniumum: 2
# read-concurrency=8

## PARTITION ###################################################
# The transactor will use this partition for new entities that
# do not explicitly specify a partition.
# Default: :db.part/user

default-partition=:db.part/${partition}

## HEARTBEAT ###################################################
# See http://docs.datomic.com/ha.html
# The transactor will write a heartbeat into storage on this interval.
# A standby transactor will take over if it sees the heartbeat go
# unwritten  for 2x this interval. If your transactor load leads to
# long gc pauses, you can increase this number to prevent the standby
# transactor from unnecessarily taking over during a long gc pause.
# Default: 5000, Miniumum: 5000
# heartbeat-interval-msec=5000
EOF

chmod 744 ddb-transactor.properties

echo "Run transactor... "
bin/transactor ddb-transactor.properties || true
echo "Transactor process stopped. Shutting down."
